'use client'
//import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import { ContextProvider } from '@/app/context/contextAuth'
import { ContextTasksProvider } from '@/app/context/contextTasks'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        <link
          rel="icon"
          type="image/svg+xml"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🗒️</text></svg>"
        />
        <title>ToDo App</title>
      </head>
      <body
        className={`${poppins.className} antialiased`}
      >
        <ContextProvider>
          <ContextTasksProvider>
            {children}
            <ToastContainer
              theme="colored"
            />
          </ContextTasksProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
